// General events
export const SHOW_TABS = 'SHOW_TABS';
export const CLOSE_ALL_TABS = 'CLOSE_ALL_TABS';
export const SHOW_DIALOG_DISCARD = 'SHOW_DIALOG_DISCARD';
export const SHOW_ERRORS = 'SHOW_ERRORS';
export const SWITCH_TAB = 'SWITCH_TAB';
export const CLOSE_TAB = 'CLOSE_TAB';
export const DISCARD_TABS = 'DISCARD_TABS';
export const OPEN_EXTENSIONS = 'OPEN_EXTENSIONS';
export const SHOW_CREDENTIALS = 'SHOW_CREDENTIALS';
export const SEARCH_TABS = 'SEARCH_TABS';
export const DISABLE_TABS = 'DISABLE_TABS';
export const MOVE_TABS = 'MOVE_TABS';

// Tab-specific errors
export const TAB_ID_NOT_FOUND = 'TAB_ID_NOT_FOUND';
export const TAB_ITEMS_NOT_FOUND = 'TAB_ITEMS_NOT_FOUND';
export const TAB_INDEX_NOT_FOUND = 'TAB_INDEX_NOT_FOUND';
export const TAB_OPEN_EXCEPTION = 'TAB_OPEN_EXCEPTION';
export const TAB_CLOSE_EXCEPTION = 'TAB_CLOSE_EXCEPTION';
export const TAB_COULD_NOT_BE_DISCARDED = 'TAB_COULD_NOT_BE_DISCARDED';
export const TABS_LOCKED = 'TABS_LOCKED';
export const TABS_COULD_NOT_BE_LOADED = 'TABS_COULD_NOT_BE_LOADED';
export const IGNORE_WARNING_DIALOG = 'IGNORE_WARNING_DIALOG';

export const RESET_ERRORS = 'RESET_ERRORS';
export const CHROME_API_EXCEPTION = 'CHROME_API_EXCEPTION';
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
